# Generated by Django 2.0.5 on 2018-05-02 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('varieties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varietyshow',
            name='air',
        ),
        migrations.AddField(
            model_name='varietyshow',
            name='air_day',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='varietyshow',
            name='air_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='varietyshow',
            name='broadcasting_station',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='varietyshow',
            name='last_modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
